### ISSUE TITLE
How to calculate the commission for a transfer transaction from a V4R2 wallet

### ISSUE THREAD

**Issue by kolevatykh** [neodix42/ton4j#10]
How to calculate the commission for a transfer transaction from a V4R2 wallet?

**Comment by neodix42** [comment]
You can use Tonlib's estimateFee method for that. Take a look a this example https://github.com/neodix42/ton4j/blob/1f5e473b7bf562412790c33c6d983b8197c48eca/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV1R3.java#L165
