### ISSUE TITLE
how to send coins using libtonjson or LiteClient?

### ISSUE THREAD

**Issue by farsait-lt** [neodix42/ton4j#12]
how to send coins using libtonjson or LiteClient?

**Comment by neodix42** [comment]
you can start from this example https://github.com/neodix42/ton4j/blob/1f5e473b7bf562412790c33c6d983b8197c48eca/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV3R2Short.java#L22

**Comment by farsait-lt** [comment]
yes v3r2 sends coins, but doesn’t attach a comment, can you tell me why? 
Is v4r2 still not ready?

**Comment by neodix42** [comment]
Thanks for reporting, the comment handling was missing in v3r2. The fix is out with version 0.4.6.
V4R2 is ready, do you have any issues?

**Comment by farsait-lt** [comment]
Yes, there is still a difficulty and a question. The difficulty lies in parsing transactions, incoming and outgoing messages in transactions are not parsed correctly - again, the commentary is not retrieved, but the question is how to send tokens (tokens)?

**Comment by neodix42** [comment]
this is how you can retrieve the comment of a tx:
https://github.com/neodix42/ton4j/blob/0a94acb6b7bd2dcdd9f41877b2249f8d8fe64227/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV3R2Short.java#L142
