### ISSUE TITLE
tell me how to see the number of tokens in an address, for example NOTcoins

### ISSUE THREAD

**Issue by farsait-lt** [neodix42/ton4j#14]
tell me how to see the number of tokens in an address, for example NOTcoins

**Comment by neodix42** [comment]
Have you looked at this example?
https://github.com/neodix42/ton4j/blob/1f5e473b7bf562412790c33c6d983b8197c48eca/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestJetton.java#L143
You have to know the jetton wallet address of token you want to manipulate.

**Comment by neodix42** [comment]
```
Tonlib tonlib = Tonlib.builder()
        .ignoreCache(false)
        .build();

log.info("balance: {}", ContractUtils.getJettonBalance(
        tonlib,
        Address.of("EQAvlWFDxGF2lXm67y4yzC17wYKD9A0guwPkMs1gOsM__NOT"),
        Address.of(<your-address-here>)
));
```
