### ISSUE TITLE
how to obtain the correct wallet v4r2 address use mnemonics

### ISSUE THREAD

**Issue by omanhom** [neodix42/ton4j#16]
**i can't get the correct wallet address using the following code,**:
Tonlib tonlib = Tonlib.builder().pathToTonlibSharedLib("~/tonlibjson.dylib").testnet(true).ignoreCache(true).build();
String mnemonicStr = "24 words mnemonic here";
List<String> mnemonics = Arrays.stream(mnemonicStr.split(" ")).toList();
Pair pair = Mnemonic.toKeyPair(mnemonics);
TweetNaclFast.Signature.KeyPair keyPair = TweetNaclFast.Signature.keyPair_fromSeed(pair.getSecretKey());
WalletV4R2 contract = WalletV4R2.builder()
        .tonlib(tonlib)
        .keyPair(keyPair)
        .walletId(0)
        .build();
Address walletAddress = contract.getAddress();
String address = walletAddress.toString(true,true,true,true);

**Comment by neodix42** [comment]
Could you please double-check if you use the correct walletId?
Do you get the correct raw address? (set user-friendly to false)

**Comment by omanhom** [comment]
thx，view typescirpt implement found the walletId  need add 698983191 and get correct
