### ISSUE TITLE
add dependency

### ISSUE THREAD

**Issue by saeedishayan76** [neodix42/ton4j#18]
hi when i add depdency to android project error duplicate class occured .
    implementation("io.github.neodix42:ton4j:0.4.6")
    implementation("io.github.neodix42.ton4j:tonlib:0.4.6")

error:

Duplicate class com.iwebpp.crypto.TweetNacl found in modules tweetnacl-java-8-0.4.6 (io.github.neodix42.ton4j:tweetnacl-java-8:0.4.6) and tweetnacl-java-8-0.4.6 (io.github.neodix42:tweetnacl-java-8:0.4.6)

**Comment by neodix42** [comment]
does it work if you add only: 
`implementation("io.github.neodix42.ton4j:tonlib:0.4.6")`

**Comment by saeedishayan76** [comment]
no new error occured

Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of io.github.andreypfau.curve25519-kotlin:curve25519-kotlin-js:0.0.4 was found. The consumer was configured to find a component for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:develop' with value 'mainnet', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.1.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:

**Comment by neodix42** [comment]
It seems you are mixing two libraries ton4j and https://github.com/andreypfau/curve25519-kotlin.
Did you add dependency to https://github.com/andreypfau/curve25519-kotlin ?

**Comment by saeedishayan76** [comment]
no just ton lib depdency exist, can i work with your library only with implementation("io.github.neodix42.ton4j:tonlib:0.4.6")?

**Comment by saeedishayan76** [comment]
so thanks, how to create wallet from mnemonic with usage of ton lib ?

**Comment by neodix42** [comment]
look at this example:
https://github.com/neodix42/ton4j/blob/aedb55acdd9c030ffaeb2143295adc5aadfa21d0/mnemonic/src/test/java/org/ton/java/mnemonic/TestMnemonic.java#L84
and afterward this one:
https://github.com/neodix42/ton4j/blob/9501c22830e09e48086c0c750cbd603aca90b1e7/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV3R2Short.java#L42v

**Comment by saeedishayan76** [comment]
thank when i add 2 depdency smartcontract and tonlib below error occured:
 Native library (com/sun/jna/android-x86-64/libjnidispatch.so) not found in resource path (.)

and when i add here file error :  dlopen failed: library "libnative-lib.so" not found android occured

**Comment by neodix42** [comment]
could you please try to use this tonlib library, compiled specifically for android:
https://cicd.neodix.io/view/pipelines/job/master-pipeline/lastSuccessfulBuild/artifact/artifacts/tonlib-android-jni/ton-android-tonlib.zip

**Comment by saeedishayan76** [comment]
Should I remove ton lib dependecny and add top folder to jni folder?

**Comment by neodix42** [comment]
No, you need tonlib dependency. Just place the library of correct
architecture to any folder or resources and specify path to it in tonlib
builder.

**Comment by fereshteh-jvz** [comment]
I added this to my project but then I faced this error: 
```java.lang.UnsatisfiedLinkError: dlopen failed: library "libtonlibjson.so" not found: needed by /data/data/com.locketwallet/cache/libnative-lib.so in namespace classloader-namespace```

> could you please try to use this tonlib library, compiled specifically for android: https://cicd.neodix.io/view/pipelines/job/master-pipeline/lastSuccessfulBuild/artifact/artifacts/tonlib-android-jni/ton-android-tonlib.zip

**Comment by neodix42** [comment]
Please double-check the path and the name of the library you are passing. 
It seems that you are mixing` libtonlibjson.so` with `libnative-lib.so`

**Comment by neodix42** [comment]
have you solved your last issue?

**Comment by neodix42** [comment]
please reopen in case the issue still valid
