### ISSUE TITLE
address parameters

### ISSUE THREAD

**Issue by farsait-lt** [neodix42/ton4j#21]
please tell me how to get a list of all tokens and their denominations belonging to the address?
Also in the address parameters there are CODE and DATA fields, what do they contain?

**Comment by neodix42** [comment]
```
Tonlib tonlib = Tonlib.builder()
        .ignoreCache(false)
        .build();

log.info("balance: {}", ContractUtils.getJettonBalance(
        tonlib,
        Address.of(<address-of-jetton-master-wallet>),
        Address.of(<your-address>)
));
```

regarding code+data fields, please read the documentation https://docs.ton.org/participate/wallets/contracts
