### ISSUE TITLE
contents of the wallet.

### ISSUE THREAD

**Issue by farsait-lt** [neodix42/ton4j#22]
Please tell me how to view all the contents of the wallet (address), the presence of tokens, collections, and in general anything else that may be there?

**Comment by neodix42** [comment]
wallet balance can be obtained using `getAccountState().`
tokens data you can get using` getJettonData()`
browse for more examples here https://github.com/neodix42/ton4j/tree/main/smartcontract/src/test/java/org/ton/java/smartcontract
