### ISSUE TITLE
Why is there an error in specifying my address to obtain transactions, and how to solve it

### ISSUE THREAD

**Issue by omanhom** [neodix42/ton4j#24]
**_the following code executes normally,when the address is changed to “**kQD6P-Dg6BoyFEdd4UFvupex_cPToZ1D6YqOrXpBG_P1GaTQ**” and get: lite server cannot return any transactions_**

Address address = Address.of("EQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N");
RawTransactions rawTransactions = tonlib.getRawTransactions(address.toString(false), null, null, 3);
for (RawTransaction tx : rawTransactions.getTransactions()) {
    if (nonNull(tx.getIn_msg()) && (!tx.getIn_msg().getSource().getAccount_address().equals(""))) {
        LastTransactionId ttx = tx.getTransaction_id();
        System.out.println(Utils.toUTC(tx.getUtime())+", "+Utils.base64ToHexString(ttx.getHash())+" "+tx.getIn_msg().getSource().getAccount_address()+" <<<<< "+tx.getIn_msg().getDestination().getAccount_address()+":"+Utils.formatNanoValue(tx.getIn_msg().getValue()));
    }
    if (nonNull(tx.getOut_msgs())) {
        for (RawMessage msg : tx.getOut_msgs()) {
            System.out.println(Utils.toUTC(tx.getUtime())+", "+ msg.getSource().getAccount_address()+" >>>> "+ msg.getDestination().getAccount_address()+":"+Utils.formatNanoValue(msg.getValue()));
        }
    }
}

**Comment by neodix42** [comment]
This simply means that the lite-server has no information about that account (block). Please try to use another lite-server. 
If you execute several times the same code you will hit once an archival node where a lite-server has all the information and then it will work.

**Comment by omanhom** [comment]
tonlib.getRawTransactions can add an parameter "archive", such astoncenter API
https://testnet.toncenter.com/api/v2/#/accounts/get_transactions_getTransactions_get

**Comment by neodix42** [comment]
toncenter checks whether the lite-server is archival or not, this is out of tonlib scope.

**Comment by omanhom** [comment]
i  try to execute several times but it still not work

how to use another lite-server?

**Comment by neodix42** [comment]
you can download
https://docs.ton.org/develop/howto/compile#download-global-config
and check which lite-server has archival data (request a block 1000 blocks
ago) and then leave only that entry in the global config.

**Comment by omanhom** [comment]
thanks, it works
