### ISSUE TITLE
macOS cannot run unit test

### ISSUE THREAD

**Issue by earth-2022** [neodix42/ton4j#26]
`10:38:31.264 [main] INFO org.ton.java.liteclient.LiteClientTest - pathToLiteClientBinary: /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe
Java Lite-Client configuration:
Location: /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe
Path to global config: /Users/bv/work/javaworkspace/ton4j/liteclient/testnet-global.config.json
Testnet: true
Jul 12, 2024 10:38:31 AM org.ton.java.liteclient.LiteClient execute
INFO: execute: /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe -t 10 -C /javaworkspace/ton4j/liteclient/testnet-global.config.json -c runmethod EQDCJVrezD71y-KPcTIG-YeKNj4naeiR7odpQgVA1uDsZqPC seqno 
10:38:31.310 [main] INFO org.ton.java.liteclient.LiteClientTest - /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe: /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe: cannot execute binary file

java.lang.AssertionError: 
Expecting actual:
/javaworkspace/ton4j/liteclient/lite-client.exe: /Users/bv/work/javaworkspace/ton4j/liteclient/lite-client.exe: cannot execute binary file
"`

**Comment by neodix42** [comment]
Why do you use windows binary file on mac? Lite-client.exe?

**Comment by earth-2022** [comment]
yes I am so confused all the unit test is base on that
