### ISSUE TITLE
Error "lite-server cannot return any transactions", reconnect to lite server

### ISSUE THREAD

**Issue by SaitgalinKhannan** [neodix42/ton4j#29]
`
if (isNull(rawTransactions.getTransactions())) {
    throw new Error("lite-server cannot return any transactions");
}
`

Why is there an Error here instead of a custom Exception? I wanted to catch an Exception and implement reconnection to another lite server.

Is it generally possible to implement reconnection to another lite server when there's no account data and transactions in the current one? (I want to try to do this, but I'm not sure if it's possible at the library level)

**Comment by neodix42** [comment]
You still can catch it with catch Error or Throwable.
Yes it is possible to write a custom reconnection mechanism. 
I also plan to add a flag to tonlib builder so tonlib could iterate automatically through a list of lite-servers.

**Comment by neodix42** [comment]
please check the new version https://github.com/neodix42/ton4j/releases/tag/0.4.9 where reconnection has been implemented.

**Comment by SaitgalinKhannan** [comment]
It`s work, thanks
