### ISSUE TITLE
Is it possible to decode msg body using ton4j??

### ISSUE THREAD

**Issue by hsmang** [neodix42/ton4j#37]
I want to decode msg body but I don't know how.
Can anyone please let me know if there is any way?

**Comment by neodix42** [comment]
yes, please take a look at this sample: https://github.com/neodix42/ton4j/blob/main/tonlib/src/test/java/org/ton/java/tonlib/TestTonlibJson.java#L367

**Comment by hsmang** [comment]
I did it the way you told me, but it wasn't the answer I wanted.
`x{D3669639FA8CA1B7B90FC53C6BC01CB6375C96016DAB67F7FC5045BBB18D06E2DC773A9393CEAFC112D398AB6CEF71365DD00875DB0B5B32FB8788F4E19AC60529A9A31766A32C52000000050003}
 x{42006F81CDEB2F2D0AD964F8E3550D019F51DBEB884E7B650FF96316CB584EA2A8D1161A800000000000000000000000000000000000313233214023262A26ED959CEAB880414243}`

I want to change the text that people can read

test transcation
https://tonscan.org/tx/gspcs5JTZmRlzKUGiOKYUx2%2F2rWXr1Gu2KBhRx7CX2Q=

plz help...

**Comment by hsmang** [comment]
CellSlice test code has been viewed.
But I don't really understand it.
Is the boc the body value of in_msg correct?
`

       String boc = "te6cckEBAgEAmwABnNNmljn6jKG3uQ/FPGvAHLY3XJYBbatn9/xQRbuxjQbi3Hc6k5POr8ES05irbO9xNl3QCHXbC1sy+4eI9OGaxgUpqaMXZqMsUgAAAAUAAwEAkEIAb4HN6y8tCtlk+ONVDQGfUdvriE57ZQ/5YxbLWE6iqNEWGoAAAAAAAAAAAAAAAAAAAAAAADEyMyFAIyYqJu2VnOq4gEFCQ6E8XQg="; //  in_msg body 


        CellSlice cellSlice = CellSlice.beginParse(CellBuilder.beginCell().fromBoc(Utils.base64ToSignedBytes(boc)).endCell());
        System.out.println("cell address : " + cellSlice.loadAddress().toString(false));
`
An error occurs when the above code is executed.

`
Exception in thread "main" java.lang.Error: Invalid address wc -101:34b1cfd4650dbdc87e29e35e00e5b1bae4b00b6d5b3fbfe2822ddd8c683716e3
	at org.ton.java.address.Address.<init>(Address.java:62)
	at org.ton.java.address.Address.of(Address.java:100)
	at org.ton.java.cell.CellSlice.loadAddress(CellSlice.java:625)
	at org.example.Main.main(Main.java:41)
`
