### ISSUE TITLE
org.ton.java.tonlib.Tonlib#getAccountState(org.ton.java.address.Address)

### ISSUE THREAD

**Issue by Hsylient** [neodix42/ton4j#41]
public static void main(String[] args) {
        Tonlib tonlib = Tonlib.builder()
//                .testnet(true)
                .ignoreCache(false)
                .build();

        FullAccountState accountState = tonlib.getAccountState(Address.of("EQCRgs1d1M91dm2hHeF8luXBH-aIF9PT-T2jlocQXiYBvAGY"));
        log.info("[Ton链测试] 地址信息 {}", accountState);
    }
    

九月 02, 2024 10:50:04 下午 org.ton.java.tonlib.Tonlib$CustomTonlibBuilder build
信息: Java Tonlib configuration:
Location: tonlibjson.dll
Verbosity level: FATAL (0)
Keystore in memory: false
Keystore path: .
Path to global config: global-config.json (integrated resource)
Global config as string: 
lite-servers found: 18
dht-nodes found: 12
init-block seqno: 34835953
using lite-servers: all
Ignore cache: false
Testnet: false
Receive timeout: 10.0 seconds
Receive retry times: 5

[ 4][t 1][2024-09-02 14:50:04.5152388][TonlibClient.cpp:2204][!Tonlib][&tonlib_query]	Tonlib got query [id:1] setLogVerbosityLevel {
  new_verbosity_level = 0
}
[ 4][t 1][2024-09-02 14:50:04.5153254][TonlibClient.cpp:2243][!Tonlib][&tonlib_query]	Tonlib got static query setLogVerbosityLevel {
  new_verbosity_level = 0
}
九月 02, 2024 10:50:04 下午 org.ton.java.tonlib.Tonlib$CustomTonlibBuilder build
信息: Using lite-server at index: 0 (5.9.10.47)

Process finished with exit code -1073741819 (0xC0000005)

**Comment by neodix42** [comment]
This is weird. Could you please show the result with 
`Tonlib.builder().verbosityLevel(VerbosityLevel.DEBUG)`

Also try to download the latest tonlibjson.dll from [here](https://github.com/ton-blockchain/ton/releases/tag/v2024.08) and specify full path to it via `.pathToTonlibSharedLib()`
