### ISSUE TITLE
java.lang.Error: can't get result by executing seqno method, exit code -13

### ISSUE THREAD

**Issue by Hsylient** [neodix42/ton4j#43]
An error occurred while executing the integration test [org.ton.java.smartcontract.integrationtests.TestWalletV3R1]. Log information: An error occurred while calling the [org.ton.java.smartcontract.wallet.Contract#getSeqno] method.

![image](https://github.com/user-attachments/assets/5c5ad550-6ad7-419f-9892-bd5c7a688702)

**Comment by neodix42** [comment]
there was a mistake in the test, please add these two lines:

![image](https://github.com/user-attachments/assets/66fa5718-8494-4c51-8e51-4d65e54b0ca1)

![image](https://github.com/user-attachments/assets/7fdad0b6-dc31-471f-898e-aaedaa281f40)

I will fix it in the next release. Thanks for reporting.
