### ISSUE TITLE
I want to use V3R1 to transfer main chain coins, but the final result is that I cannot transfer. I suspect there is a bug when transferring the mnemonic words to the address. If there is no problem, can you help me fix my demo? Thanks

### ISSUE THREAD

**Issue by Hsylient** [neodix42/ton4j#44]
public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeyException {

        Tonlib lib = Tonlib.builder()
                .testnet(true)
                .ignoreCache(false)
                .build();

        long seqno = lib.getSeqno(Address.of("0QDpUrzS2y78kSbviFXM71HGrnWOjhURL8kjNYU_UN_q96nH"));
        System.out.println(seqno);
        System.out.println(Utils.toNano(0.5));

        byte[] seed = Mnemonic.toSeed(Arrays.asList("aaaaaa", "bbbbbb",
                "xxxxx", "cccc", "ddddd", "eeeee",
                "2222", "222", "2222", "lab",
                "222", "mango", "chief", "2222",
                "2222", "zzzz", "dddd", "111", "2222",
                "222", "22", "tide", "use", "gggg"));

        TweetNaclFast.Signature.KeyPair keyPair = Utils.generateSignatureKeyPairFromSeed(seed);

        WalletV3R1 contract = WalletV3R1.builder()
                .tonlib(lib)
                .keyPair(keyPair)
                .walletId(42)
                .build();

        WalletV3Config config = WalletV3Config.builder()
                .seqno(2)
                .destination(Address.of("0QA2UlEicjKmJRu2mRJP8ZnW9G-1InGfqKag9MXuYa7W55-o"))
                .amount(Utils.toNano(0.5))
                .comment("test transfer")
                .build();

        contract.send(config);
    }

**Comment by neodix42** [comment]
try to use mnemonic words from this list?
https://github.com/neodix42/ton4j/blob/main/mnemonic/src/main/java/org/ton/java/mnemonic/Mnemonic.java#L137
