### ISSUE TITLE
tonconnect.Domain  tonconnect.TonProof  tonconnect.WalletAccount is not public. Cannot be accessed from outside package

### ISSUE THREAD

**Issue by gjgjgjgj** [neodix42/ton4j#46]
tonconnect.Domain  tonconnect.TonProof  tonconnect.WalletAccount is not public. Cannot be accessed from outside package

**Comment by neodix42** [comment]
Accepted, will be fixed in the next release

**Comment by neodix42** [comment]
please try release 0.6.0
