### ISSUE TITLE
error：library is not inited

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#48]
**{"@type":"error","code":400,"message":"library is not inited","@extra":"a8babaa7-f53e-4420-9a6f-60bd9742581e"}**
Exception in thread "main" java.lang.Error: Error in tonlib.receive(), 5 times was not able retrieve result from lite-server.
	at org.ton.java.tonlib.Tonlib.syncAndRead(Tonlib.java:396)
	at org.ton.java.tonlib.Tonlib.lookupBlock(Tonlib.java:488)

**code:**
Tonlib tonlib = Tonlib.builder()
                .pathToTonlibSharedLib("/resources/tonlibjson-mac-arm64.dylib")
                .pathToGlobalConfig("/resources/testnet-global.config.json")
                .verbosityLevel(VerbosityLevel.FATAL)
                .testnet(true)
                .build();
        long seqno = tonlib.getSeqno(Address.of("Ef86im12u4YpQiSrrJ1_VfLZA6cjOwNrji-sJwL53VZbKUQP"));
        System.out.println("===================================================================" + seqno);

**Comment by neodix42** [comment]
Hi,
I cannot reproduce your error. Did you try with the latest tonlib?
https://github.com/ton-blockchain/ton/releases/download/v2024.09/tonlibjson-mac-arm64.dylib

**Comment by a402942988** [comment]
Thank you
