### ISSUE TITLE
How to get the transaction hash when body_hash is null?

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#54]
Here are the two questions:

How can I get the transaction hash after making a transfer? When I send the transaction, the body_hash is null.
How can I retrieve the transfer result using the transaction hash?

**code:**
`Tonlib tonlib = Tonlib.builder()
                .pathToTonlibSharedLib("/resources/tonlibjson-mac-arm64.dylib")
                .pathToGlobalConfig("/resources/testnet-global.config.json")
                .verbosityLevel(VerbosityLevel.FATAL)
                .testnet(true)
                .build();
        WalletV3R2 contract1 = WalletV3R2.builder()
                .tonlib(tonlib)
                .keyPair(keyPair)
                .walletId(100)
                .build();
        WalletV3R2 contract2 = WalletV3R2.builder()
                .tonlib(tonlib)
                .keyPair(keyPair)
                .walletId(110)
                .build();

        long seqno1 = contract1.getSeqno();
        WalletV3Config config = WalletV3Config.builder()
                .walletId(100)
                .seqno(seqno1)
                .destination(Address.of(TestFaucet.BOUNCEABLE))
                .amount(Utils.toNano(0.01))
                .comment("testWalletV3R2-42-111")
                .build();

        ExtMessageInfo extMessageInfo = contract1.send(config);
        System.out.println("extMessageInfo.getError().getCode()===>" + extMessageInfo.getError().getCode()); //code=0
        System.out.println("seqno1===>" + seqno1 + ", body_hash:" + extMessageInfo.getBody_hash()); **//body_hash=null**`

**Comment by a402942988** [comment]
help!help!help!

**Comment by neodix42** [comment]
Thanks for reporting, the body_hash is missing now. This will be fixed in the next release.
Tx hash is not possible to get with a help of tonlib.
