### ISSUE TITLE
waitForBalanceChange <bug>

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#55]
Here's a bug encountered with waitForBalanceChange:

After a successful transfer, if BigInteger initialBalance = getBalance(); retrieves the balance after the transfer, it will cause an issue where the process keeps waiting indefinitely.

This happens because the initial balance is set to the post-transfer amount, making the system think no change has occurred.

**source code:**
<img width="750" alt="截屏2024-09-20 10 03 11" src="https://github.com/user-attachments/assets/072afa9d-0104-496f-9fdd-d1be54bfef01">

**Comment by neodix42** [comment]
waitForBalanceChange() should be called right after TX has been sent, in that way balance is not updated yet. Obviously if you call it with a delay you might get the status with the updated balance.

**Comment by a402942988** [comment]
Thanks!
