### ISSUE TITLE
too often got this error，Error in tonlib.receive(), 5 times was not able retrieve result from lite-server.

### ISSUE THREAD

**Issue by wood20230311** [neodix42/ton4j#57]
when I used tonlib  sdk for send a ton transaction，I got this error “Error in tonlib.receive(), 5 times was not able retrieve result from lite-server.”，why so often happen this error？ Is there a way to avoid this error?   Thanks very much！

**Comment by wood20230311** [comment]
Help！Help！Help！Help！Help！

**Comment by neodix42** [comment]
If you are using https://ton.org/global-config.json it has multiple lite-servers and ton4j's tonlib wrapper tries sequentially each lite-server. It should be a rare case when all top 5 servers are not responding in time. You can try to remove them from the global config.

**Comment by ks-39** [comment]
> If you are using https://ton.org/global-config.json it has multiple lite-servers and ton4j's tonlib wrapper tries sequentially each lite-server. It should be a rare case when all top 5 servers are not responding in time. You can try to remove them from the global config.

![123](https://github.com/user-attachments/assets/fe0d68e8-e960-43d4-aadb-dccf72757f38)
When I deploy the contract, I get a response message ："LITE_SERVER_UNKNOWN: cannot apply external message to current state: Failed to unpack account state"，and ended up with the same error as the questioner. How can i fix this problem？Please tell me！Thanks very much！

**Comment by ks-39** [comment]
> @ks-39 have you deposited initial wallet address first?

![1232323](https://github.com/user-attachments/assets/7be133eb-ee69-4ac5-85b2-ca0596cc9285)
I use keypair to build the contract, how do I deposited the initial wallet address?

**Comment by neodix42** [comment]
in testnet you can use integrated ton4j faucet 
`        BigInteger balance = TestFaucet.topUpContract(tonlib, Address.of(nonBounceableAddress), Utils.toNano(7));`

**Comment by ks-39** [comment]
> in testnet you can use integrated ton4j faucet ` BigInteger balance = TestFaucet.topUpContract(tonlib, Address.of(nonBounceableAddress), Utils.toNano(7));`

I got this error "Faucet does not have that much toncoins. faucet balance -0.000000001, requested 7.000000000"，Is something wrong?

**Comment by ks-39** [comment]
> in testnet you can use integrated ton4j faucet ` BigInteger balance = TestFaucet.topUpContract(tonlib, Address.of(nonBounceableAddress), Utils.toNano(7));`

When I run the test code： "TestPayments.java", I get the same error.....

**Comment by neodix42** [comment]
did you specify to use testnet? Faucet currently is not empty:

```
    @Test
    public void testFaucetBalance() {
        Tonlib tonlib = Tonlib.builder()
                .testnet(true)
                .ignoreCache(false)
                .build();
        FullAccountState state = tonlib.getAccountState(AccountAddressOnly.builder().account_address(FAUCET_ADDRESS_RAW).build());
        log.info("account {}", state);
        log.info("TEST FAUCET BALANCE {}", Utils.formatNanoValue(state.getBalance(), 2));
    }
```

**Comment by ks-39** [comment]
> did you specify to use testnet? Faucet currently is not empty:
> 
> ```
>     @Test
>     public void testFaucetBalance() {
>         Tonlib tonlib = Tonlib.builder()
>                 .testnet(true)
>                 .ignoreCache(false)
>                 .build();
>         FullAccountState state = tonlib.getAccountState(AccountAddressOnly.builder().account_address(FAUCET_ADDRESS_RAW).build());
>         log.info("account {}", state);
>         log.info("TEST FAUCET BALANCE {}", Utils.formatNanoValue(state.getBalance(), 2));
>     }
> ```

Thank you, I have solved this problem, the wallet id of v4r2 version is not 42 but 698983191, I found the solution at this issule：https://github.com/neodix42/ton4j/issues/16, But I don't know how this id came about....

**Comment by neodix42** [comment]
to get the walletId you can do:

Go to tonviewer.com, enter your address, go to Code tab, in the arbitrary method enter get_subwallet_id, and click execute.

**Comment by q125125** [comment]
> to get the walletId you can do:
> 
> Go to tonviewer.com, enter your address, go to Code tab, in the arbitrary method enter get_subwallet_id, and click execute.

It's too difficult, there were no prompts to tell me how to get the wallet ID. After looking at it for a few days, other languages don't even require entering the wallet ID, so I didn't think it was a problem with the wallet ID
