### ISSUE TITLE
tonhashmap cannot get

### ISSUE THREAD

**Issue by 455631680** [neodix42/ton4j#58]
![image](https://github.com/user-attachments/assets/f20f307a-5e7f-41e0-b9a8-0407e00d610c)

**Comment by 455631680** [comment]
![image](https://github.com/user-attachments/assets/9e25f709-9382-4551-8780-ade8035f55b7)
![image](https://github.com/user-attachments/assets/aed79c18-ec2a-4c56-b8c8-3dfb18f2b25d)

**Comment by 455631680** [comment]
![image](https://github.com/user-attachments/assets/6844c802-c93a-4a62-9693-232086ce90ef)

**Comment by neodix42** [comment]
please test the latest ton4j version and report back if the error still occurs
