### ISSUE TITLE
getRawTransactions not invalid in testnet

### ISSUE THREAD

**Issue by qzmer1104** [neodix42/ton4j#67]
```
String addr = Address.of("xxxxxx").toString(false);
        Tonlib tonlib = Tonlib.builder()
                .testnet(true)
                .ignoreCache(false)
                .build();
        RawTransactions txLis = tonlib.getRawTransactions(addr, null, null);
```

get 
{"@type":"error","code":500,"message":"LITE_SERVER_UNKNOWN: cannot compute block with specified transaction: cannot find block (0,1f5001ea7e5df9c4) lt=26263635000002: lt not in db","@extra":"2855c83e-21a0-4fc0-aa40-91822e4c5efe"}

**Comment by neodix42** [comment]
the block is not found in on this lite-server, you have to specify a global config that contains archival node.

**Comment by qzmer1104** [comment]
> the block is not found in on this lite-server, you have to specify a global config that contains archival node.

where to find it and how to add

**Comment by neodix42** [comment]
download [this ](https://ton.org/testnet-global.config.json)testnet global config and in tonlib builder specify path to it. One of lite-servers in this config is archival.
