### ISSUE TITLE
No demo for V5 transfer Jetton

### ISSUE THREAD

**Issue by qzmer1104** [neodix42/ton4j#68]
only v3

**Comment by neodix42** [comment]
There is an example for v4r2 - https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/TestTonSdkTestCasesSmartContracts.java#L684
Also you can refer to [this ](https://github.com/neodix42/ton-sdk-test-cases/)list for navigation.

**Comment by qzmer1104** [comment]
> There is an example for v4r2 - https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/TestTonSdkTestCasesSmartContracts.java#L684 Also you can refer to [this ](https://github.com/neodix42/ton-sdk-test-cases/)list for navigation.

I saw It。

V5Config  no destination。

and after code like this:
```
WalletV5 hotWallet = WalletV5.builder()
                .tonlib(tonlib)
                .keyPair(kp)
                .walletId(2147483409)
                .isSigAuthAllowed(true)
                .build();

WalletV5Config walletV5Config = WalletV5Config.builder()
                .seqno(hotWallet.getSeqno())
                .walletId(2147483409)
                .body(JettonWalletStableCoin.createTransferBody(
                        0,
                        BigDecimal.valueOf(1.2).multiply(BigDecimal.TEN.pow(6)).toBigInteger(),
                        Address.of("xxx"),
                        null,
                        BigInteger.ONE,
                        MsgUtils.createTextMessageBody("gift")
                        )
                )
                .build();
        ExtMessageInfo send = hotWallet.send(walletV5Config);
```
I got 
java.lang.Error: Bits overflow. Can't add 512 cell.bits. 488 bits left.

**Comment by qzmer1104** [comment]
@neodix42 help?

**Comment by neodix42** [comment]
The demo code will be added with the next release.

**Comment by neodix42** [comment]
see an example here:
https://github.com/neodix42/ton4j/blob/main/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestWalletV5.java#L1131
