### ISSUE TITLE
Message.deserialize() has a bug

### ISSUE THREAD

**Issue by 0xZonh** [neodix42/ton4j#69]
![image](https://github.com/user-attachments/assets/464d1927-7e85-4c27-bcc4-430cad282877)

When a transaction is obtained from the chain and deserialized using message.deserialize(), an error result occurs.

eg:  
1. {{ton_url}}/v2/getBlockTransactionsExt?workchain=0&shard=-6917529027641081856&seqno=26070995
2. txHash is QW+UdJfRQ7wC40T6KSrOE24hwvS0+LLd4DncGJs3qMo=

When I need to calculate the hash of out_msg and in_msg, an incorrect result will appear because the state is not empty.

When the state_init attribute is not empty, but has no value, the result is 58012802ADAD0C0E6BBD2CE17C1D01C2E5A81DEFA93D10F6E3EF721E8F4154E1440300396FA105FAF80E114BE4F60BC265A6B916ACDCD6EAFC2974 CBE576F69F3E74430E49F0000608235A000031BD250A1E04CE398B2701FFFFFFFF_

In fact, state_init should not set any value, it should be an empty object. So when state_init does not exist in the transaction, I change it to a null value, and the result is correct.
58012802ADAD0C0E6BBD2CE17C1D01C2E5A81DEFA93D10F6E3EF721E8F4154E1440300396FA105FAF80E114BE4F60BC265A6B916ACDCD6EAFC2974CBE576F69F3E74430E4 9F0000608235A000031BD250A1E04CE398B267FFFFFFFC_

But I'm not sure if there are other scenarios that I didn't consider, and I hope the author can fix it to get the correct result.

**Comment by 0xZonh** [comment]
> Thanks for reporting. At which place have you got and error? I took both transactions from {{ton_url}}/v2/getBlockTransactionsExt?workchain=0&shard=-6917529027641081856&seqno=26070995 and deserialized them without any problems:
> 
> ```
>   @Test
>   public void testTxDes() {
>     String base64boc =
>         "te6cckECCAEAAb8AA7V2Wkyx2gG8x9SjLketll0odQEG07ox8KtpoWBaeA5Vt+AAAZsagme0MggKNYRQkQ8SkUdxxexAq5rZwKyndkvHzwfl5JHgs7cwAAGbGeMkOBYpBtIAABRgMNbIAQIDAQGgBACCcgBasgAowCpcEmknNjipFnVkAEyh7FdO7kW6oe9LeSfVVBZ8LAd/L/3AIK3s1K10nMAA2LtfMImiwlSt9WEmOw8CGQxFiUVpXGegGGAw1BEGBwGzSACG1O2E8pURx/f9jXOAbp+RtgjeIQ0XBqhBsyby50zLqQAZaTLHaAbzH1KMuR62WXSh1AQbTujHwq2mhYFp4DlW35RWlcZ6AAYc4+QAADNjUEz2hMUg2kDABQBQAAAAADc2M2FlYjMxLTUwNjktNGM4ZC05OGQ3LWZiNjU2ZDE0YmRhZQCcJ8w9CQAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFvAAAAAAAAAAAAAAAABLUUtpEnlC4z33SeGHxRhIq/htUa7i3D8ghbwxhQTn44EJt5LyQ==";
> 
>     byte[] rawBoc1 = Utils.base64ToSignedBytes(base64boc);
> 
>     Cell c = CellBuilder.beginCell().fromBoc(rawBoc1).endCell();
>     Transaction tx = Transaction.deserialize(CellSlice.beginParse(c));
>     log.info("tx {}", tx);
>   }
> ```

Thank you for your reply, I may not have expressed it clearly. The txHash I have a problem with is QW+UdJfRQ7wC40T6KSrOE24hwvS0+LLd4DncGJs3qMo=. When I use its toCell() method of inMsg or outMsg, msgHash cannot be generated correctly. For example, Utils.bytesToBase64(message.toCell().hash()) cannot generate the correct msghash.

**Comment by neodix42** [comment]
where did you get this hash `QW+UdJfRQ7wC40T6KSrOE24hwvS0+LLd4DncGJs3qMo=` from?  I don't see it in the result from toncenter. 

Let's take the example I have provided, according to toncenter the output of `in_msg->body_hash` equals to "`TjwilxkpSUmf2nbyctnb9vESgfULOdyhewfMoj8TR6M=`"

result from ton4j also matches:

```
log.info("tx in_msg hash {}", Utils.bytesToBase64(tx.getInOut().getIn().toCell().getHash()));
log.info(
        "tx in_msg-body hash {}", Utils.bytesToBase64(tx.getInOut().getIn().getBody().getHash()));

INFO org.ton.java.cell.TestBocDeserealization - tx in_msg hash N/mKh08WNTGa4O30NSUPOb0h5JdZC/6pwYbE631tx6Q=
INFO org.ton.java.cell.TestBocDeserealization - tx in_msg-body hash TjwilxkpSUmf2nbyctnb9vESgfULOdyhewfMoj8TR6M=
```

FYI information, tonlib does not return txHash, it is internally generated by toncenter.

**Comment by 0xZonh** [comment]
@neodix42 

Use the following command

curl --request GET \
  --url 'https://testnet.toncenter.com/api/v2/getBlockTransactionsExt?workchain=0&shard=-6917529027641081856&seqno=26070995'

Obtain a transaction list, in which transaction_id.hash is QW+UdJfRQ7wC40T6KSrOE24hwvS0+LLd4DncGJs3qMo= and data is  te6cckECBwEAAXYAA7V5QBVtaGBzXelnC+DoDhctQO99SeiHtx97kPR6CqcKIBAAAY3pKFDwECaGi15kBA/sg+mS5AXFRbdn6kqS4yBQE7nybKbPnPtQAAGN4NmfWBZxzFkwACBgQSDoAQIDAgHgBAUAgnJQdVmYCFXS9KgXRepSXHT8e+rFn5z5+QuRNP8kfXkPQu1TOHkZ0mu5gLKdK7eCsCXnvOxGjTz0QiYLq2OyHJBWAB8ETQjmJaABwDAgjTMEEa1AAK9oAct9CC/XwHCKXyewXhMtNci1Zua3V+FLpl8rt7T586IZACUAVbWhgc13pZwvg6A4XLUDvfUnoh7cfe5D0egqnCiATmJaAAYII1oAADG9JJAMBM45ixpAAQHfBgC3WAEoAq2tDA5rvSzhfB0BwuWoHe+pPRD24+9yHo9BVOFEAwA5b6EF+vgOEUvk9gvCZaa5Fqzc1ur8KXTL5Xb2nz50Qw5J8AAGCCNaAAAxvSUKHgTOOYsmf////8AumLaq.

![image](https://github.com/user-attachments/assets/9a1851ca-dd8c-417b-a3fa-e6999948568a)


Transaction deserialize = Transaction.deserialize(CellSlice.beginParse(Cell.fromBocBase64(data)))

String msgHash = Utils.bytesToBase64(deserialize.getInOut().getIn().toCell().hash())

The msgHash result I obtained at this time is WVRWp8F8YqNBh4SvNmeJwJ5yCvRKLH5wSLAykVsWwgA=

**Comment by neodix42** [comment]
I have obtained your msghash by updating the code of Message deserialization:
```
  public static Message deserialize(CellSlice cs) {
    return Message.builder()
        .info(CommonMsgInfo.deserialize(cs))
        .init(
            cs.loadBit()
                ? (cs.loadBit()
                    ? StateInit.deserialize(CellSlice.beginParse(cs.loadRef()))
                    : StateInit.deserialize(cs))
                : null)              <-- here
        .body(
            cs.loadBit()
                ? cs.loadRef()
                : CellBuilder.beginCell().storeBitString(cs.loadBits(cs.getRestBits())).endCell())
        .build();
  }
```
The fix looks reasonable and will be available with the next ton4j release.
May I ask you where did you get this hash from `9UNypzdgZ4qSUGIQnk+ugSufV5nUtui7OYm1gMLtrn4=` ?

**Comment by 0xZonh** [comment]
Yes, the msghash generated after updating the code is correct. 

https://testnet.toncenter.com/api/v3/transactions?workchain=0&hash=416f947497d143bc02e344fa292ace136e21c2f4b4f8b2dde039dc189b37a8ca

You can use the previous txHash to query the transaction through toncenter's v3 interface. 
9UNypzdgZ4qSUGIQnk+ugSufV5nUtui7OYm1gMLtrn4= is the in_msg.hash in the result returned by this interface.
