### ISSUE TITLE
Can you update the "testnet-global.config.json" configuration file in tonlib dependency? it has only one lite-server and it always times out.....

### ISSUE THREAD

**Issue by ks-39** [neodix42/ton4j#73]

**Comment by neodix42** [comment]
yes, you can specify custom testnet global config

```
Tonlib tonlib=Tonlib.builder()
        .pathToGlobalConfig("/mnt/testnet-global.config.json")
...
```
download https://ton.org/testnet-global.config.json

ps. that one lite-server will be soon available again.

**Comment by ks-39** [comment]
> yes, you can specify custom testnet global config
> 
> ```
> Tonlib tonlib=Tonlib.builder()
>         .pathToGlobalConfig("/mnt/testnet-global.config.json")
> ...
> ```
> 
> download https://ton.org/testnet-global.config.json
> 
> ps. that one lite-server will be soon available again.

Ok, thanks for your help!
