### ISSUE TITLE
Can`t import or find LiteClient

### ISSUE THREAD

**Issue by SaitgalinKhannan** [neodix42/ton4j#74]
Hi, I can't find LiteClient in External libraries (IDEA) and can`t import him.

implementation("io.github.neodix42:smartcontract:0.7.1")
// i tried add it separatly, but it didn't work
implementation("io.github.neodix42:lite-client:0.7.1")

![image](https://github.com/user-attachments/assets/6b91bf4f-419b-4c3d-80ac-b40609abe3fc)

**Comment by neodix42** [comment]
remove hyphen "-" in the name 

https://mvnrepository.com/artifact/io.github.neodix42/liteclient/0.7.1

**Comment by SaitgalinKhannan** [comment]
Thanks, but liteclient not included in implementation("io.github.neodix42:smartcontract:0.7.1")?

**Comment by neodix42** [comment]
yes, since smartcontract module can use tonlib, lite-client is not required to work with ton smartcontracts.
