### ISSUE TITLE
WalletV5SimpleTransfer not work

### ISSUE THREAD

**Issue by Wangab** [neodix42/ton4j#83]
I encountered an error while trying to run the WalletV5SimpleTransfer example code. The error message is as follows：
`21:54:24.462 [main] INFO org.ton.java.tonlib.Tonlib -- {"@type":"error","code":500,"message":"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 50D49F7E17EC77C6212562FAF32261C61C18E8F127EDDCA4B8F6852BE652DE6F:\nexitcode=133, steps=49, gas_used=0\nVM Log (truncated):\n...SIGNU\nexecute PUSHCONT x28945F0ADB31E1F2C087\nexecute IFNOT\nexecute XCHG s2\nexecute NOT\nexecute XCHG2 s0,s7\nexecute AND\nexecute THROWIF 132\nexecute XCPU s2,s5\nexecute EQUAL\nexecute THROWIFNOT 133\ndefault exception handler, terminating vm with exit code 133\n","@extra":"cc844466-658a-481b-8184-f267bc6768bd"}
21:54:24.467 [main] INFO org.ton.java.tonlib.Tonlib -- Trying next lite-server at index: 3 (135.181.140.212)
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
21:54:25.805 [main] INFO org.ton.java.tonlib.Tonlib -- {"@type":"error","code":500,"message":"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 50D49F7E17EC77C6212562FAF32261C61C18E8F127EDDCA4B8F6852BE652DE6F:\nexitcode=133, steps=49, gas_used=0\nVM Log (truncated):\n...SIGNU\nexecute PUSHCONT x28945F0ADB31E1F2C087\nexecute IFNOT\nexecute XCHG s2\nexecute NOT\nexecute XCHG2 s0,s7\nexecute AND\nexecute THROWIF 132\nexecute XCPU s2,s5\nexecute EQUAL\nexecute THROWIFNOT 133\ndefault exception handler, terminating vm with exit code 133\n","@extra":"cc844466-658a-481b-8184-f267bc6768bd"}
21:54:25.809 [main] INFO org.ton.java.tonlib.Tonlib -- Trying next lite-server at index: 4 (135.181.140.221)
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
21:54:26.578 [main] INFO org.ton.java.tonlib.Tonlib -- {"@type":"error","code":500,"message":"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 50D49F7E17EC77C6212562FAF32261C61C18E8F127EDDCA4B8F6852BE652DE6F:\nexitcode=133, steps=49, gas_used=0\nVM Log (truncated):\n...SIGNU\nexecute PUSHCONT x28945F0ADB31E1F2C087\nexecute IFNOT\nexecute XCHG s2\nexecute NOT\nexecute XCHG2 s0,s7\nexecute AND\nexecute THROWIF 132\nexecute XCPU s2,s5\nexecute EQUAL\nexecute THROWIFNOT 133\ndefault exception handler, terminating vm with exit code 133\n","@extra":"cc844466-658a-481b-8184-f267bc6768bd"}
21:54:26.582 [main] INFO org.ton.java.tonlib.Tonlib -- Trying next lite-server at index: 5 (65.21.141.233)
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
cannot disable native stdout
cannot enable native stdout
21:54:27.386 [main] INFO org.ton.java.tonlib.Tonlib -- {"@type":"error","code":500,"message":"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 50D49F7E17EC77C6212562FAF32261C61C18E8F127EDDCA4B8F6852BE652DE6F:\nexitcode=133, steps=49, gas_used=0\nVM Log (truncated):\n...SIGNU\nexecute PUSHCONT x28945F0ADB31E1F2C087\nexecute IFNOT\nexecute XCHG s2\nexecute NOT\nexecute XCHG2 s0,s7\nexecute AND\nexecute THROWIF 132\nexecute XCPU s2,s5\nexecute EQUAL\nexecute THROWIFNOT 133\ndefault exception handler, terminating vm with exit code 133\n","@extra":"cc844466-658a-481b-8184-f267bc6768bd"}

java.lang.Error: Error in tonlib.receive(), 5 times was not able retrieve result from lite-server.

	at org.ton.java.tonlib.Tonlib.syncAndRead(Tonlib.java:426)
	at org.ton.java.tonlib.Tonlib.sendRawMessage(Tonlib.java:1327)
	at org.ton.java.smartcontract.wallet.v5.WalletV5.send(WalletV5.java:148)
	at com.wangab.bkms.TestTonService.testWalletV5SimpleTransfer1(TestTonService.java:200)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)`

**Comment by neodix42** [comment]
please check your seqno, the exitcode 133 means the wrong seqno.
https://github.com/neodix42/ton4j/blob/main/smartcontract/src/main/resources/contracts/wallets/new-wallet-v5.fc#L6

**Comment by Wangab** [comment]
> please check your seqno, the exitcode 133 means the wrong seqno. https://github.com/neodix42/ton4j/blob/main/smartcontract/src/main/resources/contracts/wallets/new-wallet-v5.fc#L6

thank you.
'long newSeq = contract.getSeqno()'，this code not work and I don't know why.
I get seqno in the following code
`
Address address=Address.of(bounceableAddress);
RunResult result=tonlib.runMethod(address,"seqno");
log.info("gas_used {}, exit_code {} ",result.getGas_used(),result.getExit_code());
TvmStackEntryNumber seqno=(TvmStackEntryNumber)result.getStack().get(0);
log.info("seqno: {}",seqno.getNumber());
`
