### ISSUE TITLE
Address serialization error occurred

### ISSUE THREAD

**Issue by 0xZonh** [neodix42/ton4j#86]
The test address 0QAAAhJkbOJYXHOtAqEVzW5chIXdpszNYuGwU4X_Eh5afLsu, 
the original format is 0:000212646ce2585c73ad02a115cd6e5c8485dda6cccd62e1b05385ff121e5a7c.

When a transaction is obtained from the chain and deserialized and parsed, MsgAddressIntStd.toString() will be called to serialize the address. But in some cases, errors will occur. As shown in the above example, when there are multiple 0s in front of the HEX result, they will be ignored when converting to bigInteger. If the length is less than 64, an error will be returned.

![image](https://github.com/user-attachments/assets/edabf731-e366-4a2b-8d81-129c2b0d9f4b)

**Comment by neodix42** [comment]
Nice catch! Thanks for reporting! This will be fixed with the next release.
