### ISSUE TITLE
Failed to create Tonlib

### ISSUE THREAD

**Issue by EronTo** [neodix42/ton4j#89]
When I try to create Tonlib, it doesn't seem to work
code：
```java
public static void main(String[] args) {
        System.out.println("111");
        try {
            Tonlib tonlib = Tonlib.builder()
                    .pathToTonlibSharedLib("/Users/eron/Work/tonlibjson-mac-arm64.dylib")
                    .pathToGlobalConfig("/Users/eron/Work/global-config.json")
                    .receiveTimeout(10.0)
                    .receiveRetryTimes(5)
                    .printInfo(true)
                    .testnet(false)
                    .build();
            System.out.println("222");

            MasterChainInfo masterChainInfo = tonlib.getMasterChainInfo();
            System.out.println(masterChainInfo);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("aaa");
    }
```
I only get 111 in the console, but no errors printed

**Comment by EronTo** [comment]
only happen with 0.8.0

**Comment by neodix42** [comment]
Thanks for reporting, could you please try with artifacts from the testnet branch?
https://github.com/ton-blockchain/ton/actions/runs/12183271678

**Comment by EronTo** [comment]
Am I supposed to use the libtonlibjson.dylib from it? But I still encountered the same problem.

**Comment by neodix42** [comment]
please take a look at this question, https://github.com/neodix42/ton4j/issues/92
let me know if it helped

**Comment by EronTo** [comment]
> please take a look at this question, #92 let me know if it helped

Thank you, it's working fine.
