### ISSUE TITLE
How submitting transactions of USDT in TON 

### ISSUE THREAD

**Issue by XiaoQin0000** [neodix42/ton4j#9]
How submitting transactions of USDT in TON

**Comment by neodix42** [comment]
Take a look at this example here:
https://github.com/neodix42/ton4j/blob/1f5e473b7bf562412790c33c6d983b8197c48eca/smartcontract/src/test/java/org/ton/java/smartcontract/integrationtests/TestJettonStableCoin.java#L113

**Comment by XiaoQin0000** [comment]
您好，我是王钦誉，已收到您的来信，会尽快给您回复。如有问题请致电:18826270227/66227
