### ISSUE TITLE
Using tonlib, can an RPC address be used instead of a configuration file?

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#95]
Using tonlib, can an RPC address be used instead of a configuration file?

If possible, could you please provide the TON RPC addresses, including those for the testnet and mainnet?

**Comment by a402942988** [comment]
The configuration file contains only IP addresses. What should be done if they are changed? Is it possible to use RPC to replace them? Thank you for the guidance.

**Comment by neodix42** [comment]
RPC usage is impossible with tonlibjson, you should consider using https://toncenter.com/ for that.
The configuration file contains not only IP addresses but also a public key for each lite-server

**Comment by a402942988** [comment]
Thank you
