### ISSUE TITLE
Is there a way to avoid reloading every time the system restarts? Thank you for letting me know.

### ISSUE THREAD

**Issue by a402942988** [neodix42/ton4j#96]
Is there a way to avoid reloading every time the system restarts? Thank you for letting me know.
<img width="804" alt="截屏2024-12-24 10 19 13" src="https://github.com/user-attachments/assets/861e26c8-e08a-4713-bd5b-ced68dac27bc" />

**Comment by neodix42** [comment]
try to use:
```
Tonlib.builder()
    .ignoreCache(false)
```
